services:
  - type: web
    name: blitz-on-render
    env: node
    plan: starter
    buildCommand: yarn; blitz db migrate
    startCommand: blitz start --production -H 0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blitz-on-render-db
          property: connectionString

databases:
  - name: blitz-on-render-db
    plan: starter
